name: Scheduler

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update sponsors.svg
        run: npx sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.TOKEN_SPONSORS }}
          SPONSORKIT_GITHUB_LOGIN: wangkanai
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_KEY }}
          SPONSORKIT_OPENCOLLECTIVE_SLUG: wangkanai

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
